version: 2
updates:
    - package-ecosystem: "gomod"
      directory: "/src"
      schedule:
        interval: "weekly"
      open-pull-requests-limit: 10
      rebase-strategy: "auto"
    - package-ecosystem: "docker"
      directory: "/docker"
      schedule:
        interval: "weekly"
      open-pull-requests-limit: 10
      rebase-strategy: "auto"
    - package-ecosystem: "github-actions"
      directory: "/.github/workflows"
      schedule:
        interval: "weekly"
      open-pull-requests-limit: 10
      rebase-strategy: "auto"