name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  prepare:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - name: DEBUG
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
        echo "GITHUB_SHA: $GITHUB_SHA"
        echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
        echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  release:
    needs: prepare

    env:
      GO_VERSION: 1.23.4
      SRC_PATH: ${{ github.workspace }}/src
      ARTIFACT_NAME: bshc-prometheus-exporter
      ARTIFACT_PATH: ${{ github.workspace }}/bin

    permissions:
      contents: write
      packages: write
      id-token: write

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Prepare Env
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          GOOS=linux
          GOARCH=amd64
        elif [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
          GOOS=linux
          GOARCH=arm64
        else
          echo "Unsupported OS: ${{ matrix.os }}"
          exit 1
        fi

        ARTIFACT_FULL_NAME=${{ env.ARTIFACT_NAME }}-${{ github.ref_name }}-${GOOS}-${GOARCH}

        echo "GOOS=${GOOS}" >> $GITHUB_ENV
        echo "GOARCH=${GOARCH}" >> $GITHUB_ENV
        echo "ARTIFACT_FULL_NAME=${ARTIFACT_FULL_NAME}" >> $GITHUB_ENV
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install dependencies
      run: go mod download && go mod verify
      working-directory: ${{ env.SRC_PATH }}

    - name: Build project
      run: go build -v -o ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_FULL_NAME }} ./...
      working-directory: ${{ env.SRC_PATH }}

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_FULL_NAME }}
        asset_name: ${{ env.ARTIFACT_FULL_NAME }}
        asset_content_type: application/octet-stream

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: image=moby/buildkit:v0.21.0

    - name: Debug Buildx
      run: docker buildx inspect

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/docker/Dockerfile
        platforms: linux/arm64,linux/amd64
        tags: |
          ghcr.io/plasticghoul/${{ env.ARTIFACT_NAME }}:latest
          ghcr.io/plasticghoul/${{ env.ARTIFACT_NAME }}:${{ github.ref_name }}
        push: true
        no-cache: true
        build-args: |
          ARTIFACT_NAME=${{ env.ARTIFACT_FULL_NAME }}
 